version: "3"

services:
  mariadb:
    image: mariadb:10
    volumes:
      - ./data/db:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
  phpfpm:
    image: johnpbloch/phpfpm:7.2
    depends_on:
      - mariadb
    env_file:
      - .env
    volumes:
      - ./web/wp:/var/www/html
      - ./web/wp-config.php:/var/www/html/wp-config.php
      - ./config/phpfpm/php.ini:/usr/local/etc/php/php.ini
  nginx:
    image: nginx:1
    depends_on:
      - phpfpm
    ports:
      - 80:80
    volumes:
      - ./web/wp:/var/www/html
      - ./log/nginx:/var/log/nginx
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
